name: Update SmartDNS Rules

on:
  schedule:
    # 每 6 小时执行一次 (UTC 0:00, 6:00, 12:00, 18:00)
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发
  push:
    paths:
      - 'mylist.txt'
      - 'update.sh'
      - 'update_chinalist.sh'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 生成国内域名分流列表
        run: |
          chmod +x update_chinalist.sh
          ./update_chinalist.sh

      - name: 生成广告黑名单过滤规则
        run: |
          chmod +x update.sh
          ./update.sh

      - name: 提交并推送到 GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add chinalist.txt smartdns_ad_block.conf

          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update SmartDNS Rules"
            git push
          else
            echo "规则没有变化，无需提交"
          fi
