name: Update SmartDNS AdBlock List

on:
  schedule:
    # 每天北京时间早上 6 点自动运行 (UTC 时间 22:00)
    - cron: '0 22 * * *'
  workflow_dispatch: # 允许在 GitHub 网页上手动点击运行

permissions:
  contents: write # 允许 Action 推送代码到仓库

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 运行合并脚本
        run: |
          chmod +x update.sh
          ./update.sh

      - name: 提交并推送到 GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add smartdns_ad_block.conf
          
          # 检查是否有内容变更，如果有则提交
          if ! git diff-index --quiet HEAD; then
            git commit -m "Auto Update SmartDNS AdBlock Rules"
            git push
          else
            echo "规则没有变化，无需提交"
          fi
